name: Build library

on:
  push:
    branches:
      - master
      - version-[0-9].[0-9]+.x
    tags:
      - v[0-9].[0-9]+.[0-9]+
  pull_request:

jobs:
  build-native:
    runs-on: ${{ matrix.os }}
    env:
      target-path: ${{ matrix.platform }}-${{ matrix.arch }}
    strategy:
      matrix:
        platform: [linux, win32, darwin]
        arch: [x86, x86-64, aarch64]
        exclude:
          - platform: darwin
            arch: x86
          - platform: win32
            arch: aarch64
        include:
          - platform: darwin
            os: macos-latest
          - platform: linux
            os: ubuntu-18.04
          - platform: linux
            arch: aarch64
            extra-packages: gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          - platform: linux
            arch: x86
            extra-packages: gcc-5 g++-5 gcc-5-multilib g++-5-multilib
          - platform: linux
            arch: x86-64
            extra-packages: gcc-5 g++-5
          - platform: win32
            os: ubuntu-20.04
            extra-packages: mingw-w64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install build tools
        if: ${{ matrix.extra-packages }}
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.extra-packages }}
      - run: |
          git submodule init
          git submodule update
      - name: Build native image
        run: |
          export LEVELDB_ARCH=${{ matrix.target-path || env.target-path }}
          if [[ -f $(pwd)/toolchains/$LEVELDB_ARCH ]]; then
            export LEVELDB_TOOLCHAIN=$(pwd)/toolchains/$LEVELDB_ARCH
          fi
          ./bin/build_leveldb.sh
          ls -la vendor/leveldb/build
          ls -R leveldb-jna-native/src/main/resources
      - name: Upload native image
        uses: actions/upload-artifact@v2
        with:
          name: native-images.zip
          path: leveldb-jna-native/src/main/resources/*
  build-core:
    runs-on: ubuntu-20.04
    needs: [build-native]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ hashFiles('pom.xml') }}
          path: ~/.m2/repository
      - name: Prepare version
        id: maven-version
        run: |
          mvn_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git_ref=${GITHUB_REF##*/}
          pr_number=${{ github.event.number }}
          if [[ $git_ref =~ v[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
            if [[ v$mvn_version != $git_ref ]] ; then
              echo Maven version $mvn_version does not match tag $git_ref
              exit 1
            fi
          elif [[ $pr_number != "" && $mvn_version =~ -SNAPSHOT$ ]] ; then
            pattern="s/(.+)-SNAPSHOT/\1-"$pr_number"-SNAPSHOT/g"
            mvn_version=$(echo $mvn_version | sed -E $pattern)
            mvn versions:set -DnewVersion=$mvn_version -DgenerateBackupPoms=false -q -DforceStdout
          elif [[ ! $mvn_version =~ -SNAPSHOT$ ]] ; then
            echo Refusing to publish non-snapshot version $mvn_version
            echo '::set-output name=skip-publish::true'
          fi
      - uses: actions/download-artifact@v1
        with:
          name: native-images.zip
          path: leveldb-jna-native/src/main/resources/
      - run: ls -R leveldb-jna-native/src/main/resources
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: samuelmeuli/action-maven-publish@v1.4.0
        if:
          ${{ steps.maven-version.outputs.skip-publish != 'true' }}
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_KEY_ASCII }}
          gpg_passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
